# Generated by Django 6.0.2 on 2026-02-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='creci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
