# Generated by Django 6.0.2 on 2026-02-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0002_alter_corretor_creci_alter_corretor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='creci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
