# Generated by Django 6.0.2 on 2026-02-14 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0003_alter_corretor_creci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('quartos', models.PositiveIntegerField(default=0)),
                ('banheiros', models.PositiveIntegerField(default=0)),
                ('vagas_garagem', models.PositiveIntegerField(default=0)),
                ('area_m2', models.FloatField()),
                ('finalidade', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], default='venda', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='anuncios/')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
